
[ElementalConversion]
	#Whenever a vanilla damage is compatible in theme with the mod custom elements, it will convert that partially, for example, Fall damage is turned into earth, freezing into ice etc. This option controls that as a whole
	"Convert Elemental damage" = true
	#Freezing damage turns into Ice Damage
	"Convert Ice damage" = true
	#How much damage is transferred into elemental damage 0 for 0% and 1 for 100%
	"Ice damage percentage conversion" = 0.95
	#Lava,In/OnFire, fireball, dragon breath(50%) turns into Fire damage
	"Fire Conversion" = true
	#How much damage is transferred into elemental damage 0 for 0% and 1 for 100%
	"Fire Conversion Percentage" = 0.95
	#Thunder, dragon breath(50%) turns into Electrical damage
	"Electrical Conversion" = true
	#How much damage is transferred into elemental damage 0 for 0% and 1 for 100%
	"Electrical Conversion Percentage" = 0.75
	#Anvil, Stalagmite, Fall and kinetic damage turns into Earth damage
	"Earth Conversion" = true
	#How much damage is transferred into elemental damage 0 for 0% and 1 for 100%
	"Earth Conversion Percentage" = 0.95
	#This makes earth conversion to also inflict Earth Crush which deals area Earth damage 
	"Earth Conversion Crush" = false
	#No damage converts into water damage, this is a placeholder
	"Water Conversion" = true
	#How much damage is transferred into elemental damage 0 for 0% and 1 for 100%
	"Water Conversion Percentage" = 0.75

[Elements]
	#Ice damage slows target
	"Ice Can Slow" = true
	#How strong is ice slow, damage required per level
	"Ice Slow Power" = 10.0
	#Amount of ticks of slow per damage point
	"Ice Slow Duration" = 20.0
	#Fire Damage stacks infinitely with the combustion debuff increasing damage overtime
	"Fire Combustion" = true
	#How much combustion ticks are inflicted per Fire damage
	"Fire Combustion Duration" = 15.0
	#How much seconds are needed to grant a 100% increase
	"Fire Combustion Power" = 400.0
	#Allows for electrical damage to ricochet into nearby entities that are not the original attacker or tamed by it-
	"Electrical Ricochet" = true
	#If true, ricochet will lose damage by a percentage, else will lose by a base amount
	"Electrical Ricochet decrement" = true
	#If decrement is true, this value will be used
	"Electrical Ricochet Percentage" = 0.75
	#if decrement is false, this value will be used
	"Electrical Ricochet Flat" = 1.25
	#If decrement is porcentual, this is the minimal damage to ricochet
	"Electrical Ricochet Minimal Amount" = 2.5
	#How much blocks ricochet can travel per electrical damage (Diameter)
	"Electrical Ricochet Reach" = 1.5
	#Allows Water element to inflict Wet effect, which interacts with other elements
	"Allows Water element to inflict Wet effect, which interacts with other elements" = true
	#How much ticks per Water damage Wet affects
	WaterWetDuration = 40.0
	#How much water damage is needed per extra wet level
	"Water Wet Power" = 20.0
	#Allows earth crush, effect inflicted by bosses, and some weapons. Deals damage in a circle around the target similar to Minecraft vanilla mace
	"Earth Crush" = true
	#How much Earth damage is needed per a block of radius reach
	"Earth Crash Radius" = 5.0
	#Earth defence increases damage of Earth crash, how many points of armor per damage
	"Earth Crash Weigth" = 1.0

[Permafrost]
	#Allows blizzards to happen naturally, they are forced upon certain events
	"Allow Blizzards" = true
	#How many odds for a blizzard to happen per day (accumulates each day) (in %)
	"Blizzard odds" = 10.0
	#How much a blizzard last for, the higher value the longer, (in %)
	"Blizzard Duration" = 100.0
	#Alows one to be affected by temperature on permafrost
	"Permafrost Temperature" = true
	#Increases the player resistance to temperature (in %)
	"Permafrost Temperature Resistance" = 100.0
	#Controls if the player needs to defeat Avariel to break the labyrinth structure
	"Allow Permafrost labyrinth Break" = true

